package installer

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// Keep the package-manager-owned `codex` executable untouched. Interactive
// shells use a function; subprocesses and `command codex` still find the CLI.
func (e *Engine) prepareEntry(p *Plan, python, codex, panel string, put func(string, []byte, fs.FileMode) error, get func(string) (*Change, error)) error {
	entry, err := e.target("data", "codex-panel/codex_entry.py")
	if err != nil {
		return err
	}
	wrapperPath, err := e.target("bin", "codex-with-panel")
	if err != nil {
		return err
	}
	wrapper := "#!/bin/sh\n# Generated by codex-setup; original codex executable is never replaced.\n" +
		"if [ -z \"${CODEX_HOME:-}\" ]; then export CODEX_HOME=" + shellQuote(e.CodexHome) + "; fi\n" +
		"if [ -z \"${CODEX_PANEL_REAL_CODEX:-}\" ]; then export CODEX_PANEL_REAL_CODEX=" + shellQuote(codex) + "; fi\n" +
		"export CODEX_PANEL_LAUNCHER=" + shellQuote(panel) + "\n" +
		"exec " + shellQuote(python) + " " + shellQuote(entry) + " \"$@\"\n"
	if err = put(wrapperPath, []byte(wrapper), 0755); err != nil {
		return err
	}
	snippet := "# >>> codex-setup:launcher >>>\n" +
		"# Interactive shells only; automation and the official executable stay unchanged.\n" +
		"case $- in\n" +
		"  *i*)\n" +
		"    unalias codex 2>/dev/null || :\n" +
		"    function codex {\n" +
		"      " + shellQuote(wrapperPath) + " \"$@\"\n" +
		"    }\n" +
		"    ;;\n" +
		"esac\n" +
		"# <<< codex-setup:launcher <<<"
	for _, file := range []string{filepath.Join(e.Home, ".bashrc"), e.zshHookPath()} {
		c, err := get(file)
		if err != nil {
			return fmt.Errorf("no se puede integrar el launcher en %s: %w", file, err)
		}
		updated, err := shellBlock(c.data, snippet)
		if err != nil {
			return fmt.Errorf("%s: %w", file, err)
		}
		if err = put(file, updated, 0644); err != nil {
			return err
		}
		p.Warnings = append(p.Warnings, "Integración del comando codex en "+file+" (solo shell interactivo; se conserva el resto del archivo).")
	}
	p.Warnings = append(p.Warnings, "Abre una terminal nueva después de instalar. codex abrirá el panel; CODEX_PANEL_DISABLE=1 codex o command codex omite el panel. No se cambia el ejecutable oficial.")
	return nil
}

func (e *Engine) zshHookPath() string {
	root := e.Home
	// A staged --home must never inherit the current user's live ZDOTDIR.
	if actual, err := os.UserHomeDir(); err == nil && filepath.Clean(actual) == e.Home {
		if custom := os.Getenv("ZDOTDIR"); filepath.IsAbs(custom) && filepath.Clean(custom) != string(filepath.Separator) {
			root = custom
		}
	}
	rc := filepath.Join(root, ".zshrc")
	if info, err := os.Lstat(rc); err == nil && info.Mode()&os.ModeSymlink != 0 {
		// Nix/Home Manager often owns .zshrc. Do not mutate/dereference it.
		return filepath.Join(root, ".zshenv")
	}
	return rc
}

func shellBlock(existing []byte, snippet string) ([]byte, error) {
	const start = "# >>> codex-setup:launcher >>>"
	const end = "# <<< codex-setup:launcher <<<"
	text := string(existing)
	a, b := strings.Index(text, start), strings.Index(text, end)
	if strings.Count(text, start) > 1 || strings.Count(text, end) > 1 || ((a < 0) != (b < 0)) || (a >= 0 && b < a) {
		return nil, fmt.Errorf("bloque de launcher incompleto o duplicado; revisa el archivo antes de instalar")
	}
	if a >= 0 {
		return []byte(text[:a] + snippet + text[b+len(end):]), nil
	}
	if strings.TrimSpace(text) == "" {
		return []byte(snippet + "\n"), nil
	}
	return []byte(strings.TrimRight(text, "\n") + "\n\n" + snippet + "\n"), nil
}
