model = "gpt-6-astra"
model_reasoning_effort = "medium"
forced_login_method = "chatgpt"
service_tier = "default"

[features]
multi_agent = true
multi_agent_v2 = true
apps = false
hooks = false
plugin_sharing = false
plugins = false
remote_plugin = false
skill_mcp_dependency_install = false
workspace_dependencies = false
js_repl = false

[tui]
theme = "dracula"
